### ISSUE TITLE
Zoom option

### ISSUE THREAD

**Issue by cpitman-11** [BranniganLab/blobulator#11]
Should be able to zoom in on the blobs

- knb84

**Comment by gbrannigan** [comment]
Needed for efficiency as well as ease of view. 

1) Need an interface for zoomed region. 
2) Need to actually zoom in in a way that non-visible residues are not updated and do not add to visualization time.

**Comment by EzryStIago** [comment]
Working on a two-thumb slider

**Comment by EzryStIago** [comment]
Update: switching to jquery range slider

**Comment by EzryStIago** [comment]
Exciting news!
Zooming is now live on the dev site. (click and drag to zoom, double click to zoom out)
The beast: P21817 now updates in 2 to 3 seconds (down from 12 on the live site) WITHOUT zooming. I'm not 100% sure why, but I think it's to do with the d3-ify-ing (replacing elements of plain JS with d3 equivalents).
Known issues:
Skylines don't update when zoomed in
Zooming is independent between figures
Need to add a "reset all" button and some documentation.
