### ISSUE TITLE
Information Icon

### ISSUE THREAD

**Issue by cpitman-11** [BranniganLab/blobulator#119]
Add the "i" surrounded by a circle icon for the tooltips

**Comment by EzryStIago** [comment]
I don't have this problem locally, but I replaced the literal info icon with the equivalent unicode id (1F6C8). This change is committed in the branch https://github.com/BranniganLab/blobulator/tree/infoFix
@cpitman-11 Have you had this issue? Can you check to see if that branch fixes the issue?
