### ISSUE TITLE
Headers/Tabs

### ISSUE THREAD

**Issue by cpitman-11** [BranniganLab/blobulator#121]
Add the headers/tabs from the front page to the blobulator output page

**Comment by EzryStIago** [comment]
I've begun working on this. A brute force fix would be to copy and paste the header and tab info from tabs.html to index.html, but that's very poor practice, of course. I've been trying to figure out how to make the results section a tab by itself inside the home page, but I haven't found a clean solution. @ttjoseph Do you have any insight?
