### ISSUE TITLE
Globular tendency plot is cut off on right side

### ISSUE THREAD

**Issue by ttjoseph** [BranniganLab/blobulator#13]
The legend at the right side of the second plot is cut off:

![image](https://user-images.githubusercontent.com/167129/121744973-b34bd880-cad1-11eb-8d1e-8398b796c997.png)

**Comment by ttjoseph** [comment]
(MS Edge 90.0.818.41 on Mac)

**Comment by EzryStIago** [comment]
I rephrased the legend. This is no longer an issue locally
![screenshot_Aug30](https://user-images.githubusercontent.com/13633194/131350871-a5bff5bb-2595-4fe1-9fbc-7e5039d9ea85.png)
