### ISSUE TITLE
Miscellaneous Tab Cleanups

### ISSUE THREAD

**Issue by gbrannigan** [BranniganLab/blobulator#132]
Move "Result" next to "New Query"
Add a tab back to the Brannigan Lab Homepage.

**Comment by gbrannigan** [comment]
@ttjoseph I was thinking that "Result" should be next to Query but maybe that is not easy since it is a new tab that pops up. Could you clarify?

**Comment by ttjoseph** [comment]
@gbrannigan The tabs that show on the the home page are one jinja template block, so doing this would require splitting those up and complicating the templates...so it's not a minor tweak as far as I can tell.

**Comment by EzryStIago** [comment]
Tab order: 4ddc9222e0234f2dab576752487ab0a9d3d50baf
Link back: 96d4869a5d01db2ee81e29694a368a5e4887816a
