### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by ruchilohia** [BranniganLab/blobulator#133]
Currently running compute_blobs.py is outputting runtimes. That needs to be cleaned up. Also make sure that when the user runs compute_blobs.py (as instructed in the README), the dataframe does not ouput extra columns.
Steps for running blobulator locally:
install conda
conda create --name blobulator_env python=3.9
conda activate blobulator_env
pip install  wtforms
pip install pandas
pip install matplotlib
pip install flask
pip install flask_restful
pip install flask_cors
pip install flask_session
pip install requests
pip install svglib
python blobulation.py

**Comment by ttjoseph** [comment]
I've added a pip `requirements.txt` in commit 6b82dad to make it easier for user to install the python module dependencies.

**Comment by EzryStIago** [comment]
Commented out the timing outputs in commit https://github.com/BranniganLab/blobulator/commit/f262c53c2e5d21f949326aa4b34e55ee3d97437e

Does this address your concern, @ruchilohia?
