### ISSUE TITLE
"Info" icons overlap data display area

### ISSUE THREAD

**Issue by mebh** [BranniganLab/blobulator#136]
The info icon overlaps the mean hydropathy bars for some proteins/blobulation paramters. Looks like the icon placement is ok for the other plots. 

<img width="1089" alt="Screen Shot 2021-11-14 at 4 50 08 PM" src="https://user-images.githubusercontent.com/1388592/141701157-64287e4d-82cb-47ce-9c51-4f27fdb9b5a4.png">

**Comment by ttjoseph** [comment]
If we move it further to the right, we'd want to do it for all the plots, and then they'd overlap the legends.

**Comment by gbrannigan** [comment]
Can it be moved up?

**Comment by EzryStIago** [comment]
This was addressed by Connor in commit #157
