### ISSUE TITLE
Feature request: Allow for protein queries using common gene IDs other than UniProt

### ISSUE THREAD

**Issue by mebh** [BranniganLab/blobulator#138]
Few genomics tools routinely provide UniProt IDs for variants located in genes, so only allowing for UniProt IDs is a bit of a bother. It'd be great if the user could enter any of the following types of IDs that are common for human genetics research, and let the tool figure out the corresponding UniProt entry (if there is one):

1. HGNC symbol names from the HUGO nomeclature committee: https://www.genenames.org/
2. Ensembl gene ids: https://www.ebi.ac.uk/training/online/courses/ensembl-browsing-genomes/navigating-ensembl/investigating-a-gene/
3. RefSeq gene ids
4. UCSC gene ids

A general search based on gene name or any of the above would be ideal. The above is probably the order of types of ids that I'd normally want to use. UniProt ids are not commonly used in a lot of human genomics research, unless there is an overriding reason not to use one of the above.  

Eventually, it'd be very cool if the blobulator could use a transcript id (e.g. Ensembl transcript ids) and then display the corresponding translated protein.

**Comment by gbrannigan** [comment]
How this would work: Option 1 becomes Database Entry instead of uniprot
Pull-down menu of possible databases
User adds accession number.
