### ISSUE TITLE
New track: blob type

### ISSUE THREAD

**Issue by gbrannigan** [BranniganLab/blobulator#140]
Very first track below hydropathy scale
Colors based on h, p, and s blobs (orange, blue, green)

**Comment by gbrannigan** [comment]
Can you please make the orange #F7931E, blue #0071BC, and green #2DB11A to match the established colors?

**Comment by gbrannigan** [comment]
Also (this was my fault) but h should be blue and p should be orange.

**Comment by cpitman-11** [comment]
fixed in commit 26c2acd
