### ISSUE TITLE
Add option to blobulate the protein with given SNP

### ISSUE THREAD

**Issue by ruchilohia** [BranniganLab/blobulator#15]

**Comment by ruchilohia** [comment]
Have added a basic version for this. If it looks okay I will add do enhancements as next step

**Comment by EzryStIago** [comment]
Typo: "muate"

The interface is not clear - maybe add a label that says "residue position" and change 'amino acid' to 'Target Amino Acid'

To get the mutation to update the figures, I have to uncheck and then recheck the option.

Download plots and download data don't update.

**Comment by ttjoseph** [comment]
See PR #25 which I believe addresses this.
