### ISSUE TITLE
Make compute_blobs.py accept command line arguments for FASTA inputs and config files

### ISSUE THREAD

**Issue by EzryStIago** [BranniganLab/blobulator#155]
Currently, "python3 compute_blobs.py" just blobulates an example sequence. I think users should be able to provide one or more FASTA files and set cutoffs without having to modify the python code directly.

**Comment by ttjoseph** [comment]
@EzryStIago will use argparse to parse command line arguments

**Comment by EzryStIago** [comment]
Working version in batchJobs: https://github.com/BranniganLab/blobulator/commit/4ad880a534022246ab6fa1723310577059f04987

**Comment by cpitman-11** [comment]
@mebh - could you please test this feature?
