### ISSUE TITLE
Add note that large proteins may take up to a minute to blobulate

### ISSUE THREAD

**Issue by EzryStIago** [BranniganLab/blobulator#156]
Add "Please wait, loading" and hourglasses or similar when the back-end is doing something not immediately apparent to the user.

**Comment by ttjoseph** [comment]
This would require reworking how the results page is displayed. Currently it's a form submission that returns a whole new page. A loading icon would need this to change to a full on REST API approach. Maybe not the highest yield for the milestone due date...

**Comment by gbrannigan** [comment]
Fair enough!

**Comment by cpitman-11** [comment]
Add note that large proteins may take up to a minute to blobulate

**Comment by gbrannigan** [comment]
I think we completed this?
