### ISSUE TITLE
Regression Tests

### ISSUE THREAD

**Issue by gbrannigan** [BranniganLab/blobulator#161]
Need to develop a testing checklist for merging into main branch.

**Comment by EzryStIago** [comment]
Results tab:
- Updates:
For each of the following, do blobs change height? Do they change color?
-- Mutation button
-- Mutation drop-down menu
-- Hydropathy slider
-- Blob size slider
-- Hydropathy numerical input
-- Blob size numerical input
-- Hydropathy up/down buttons
-- Blob size up/down buttons

**Comment by gbrannigan** [comment]
For two proteins check that the blobulation (at the default parameters) remains unchanged.

**Comment by gbrannigan** [comment]
check:
- download plots
- download data

**Comment by EzryStIago** [comment]
Moved to wiki
