### ISSUE TITLE
Implement Change Log

### ISSUE THREAD

**Issue by gbrannigan** [BranniganLab/blobulator#165]
Make a CHANGES file in the Production Branch
Then either: 
1) Make a tabbed page that echos from the CHANGES file
2) Or just add a link to the file in Footer

**Comment by EzryStIago** [comment]
Added link to footer.

**Comment by EzryStIago** [comment]
In commit https://github.com/BranniganLab/blobulator/commit/c6d7ae3fe7c34691c3e06911ed08c6e0021290d9
