### ISSUE TITLE
Ghost SNP

### ISSUE THREAD

**Issue by gbrannigan** [BranniganLab/blobulator#168]
For this protein, hovering around residue 400 lets you click on some invisible SNPs.  Reproduced by Matt. Parameters don't seem to matter.  

![image](https://user-images.githubusercontent.com/10160176/142968882-0a194abf-dea2-4a33-b338-5993ec3253ca.png)

**Comment by gbrannigan** [comment]
Same protein, @mebh reports an additional ghost SNP around 300 that takes him to gnomAD!

**Comment by EzryStIago** [comment]
Fixed with commit https://github.com/BranniganLab/blobulator/commit/ff3e119c4d67b75aa7f5bfbae6b8157fd666e6bc
