### ISSUE TITLE
Blob output file needs to include Kyte-Dolittle values for each residue, and <H> needs to be spelled out as mean blob hydrophobicity

### ISSUE THREAD

**Issue by gbrannigan** [BranniganLab/blobulator#170]
I got very confused by < H > (see below) - I thought it was the KD value because of course that should be in the output, and I didn't realize that < H > was for the blob because it was never spelled out that way and we actually never plot it! 

![image](https://user-images.githubusercontent.com/10160176/143786462-70b42585-3a11-48bd-88ac-e8f77d4a53c7.png)

**Comment by EzryStIago** [comment]
See branch: [csvRevision](https://github.com/BranniganLab/blobulator/tree/csvRevision)
