### ISSUE TITLE
Link in wrong place 

### ISSUE THREAD

**Issue by gbrannigan** [BranniganLab/blobulator#172]
![image](https://user-images.githubusercontent.com/10160176/144628486-eb2ad46a-3876-4eb1-94ba-17f423ec79f0.png)

"Manuscript in preparation" shouldn't link to bioarxiv.  
The title of the manuscript itself should link to bioarxiv. 

Why? Because "manuscript in preparation" refers to the Blobulator paper that Connor is currently writing, not the one that is already out.

**Comment by cpitman-11** [comment]
Resolved in commit 53c8749
