### ISSUE TITLE
Swap top and middle tracks in the screenshot below

### ISSUE THREAD

**Issue by gbrannigan** [BranniganLab/blobulator#179]
![image](https://user-images.githubusercontent.com/10160176/144701826-1d1f40d6-976b-4fb7-a126-ea95d5e58618.png)

**Comment by EzryStIago** [comment]
Addressed in commit: https://github.com/BranniganLab/blobulator/commit/0690f1b533f6ad2f67eab41eb89add2ae0a6f05f
