### ISSUE TITLE
Constrain colorbar scale on Uversky track to go between -1 and 1

### ISSUE THREAD

**Issue by gbrannigan** [BranniganLab/blobulator#180]

**Comment by gbrannigan** [comment]
It should be fixed and symmetric around 0. The scale below suggests that it is determined differently for each protein.

![image](https://user-images.githubusercontent.com/10160176/144716424-4ae1cbba-d4f2-438d-a7e9-0b5aedd207ff.png)

**Comment by EzryStIago** [comment]
I believe @cpitman-11 hard-coded these values because of the accessible range in the Uversky plot. 
We can:
A) Rescale the colormap to run -1 to 1 (despite the extremes being inaccessible)
B) Rescale the scores to run -1 to 1 (e.g. f(x)=2(x+0.65)/1.38 - 1 = 1.45*x - 0.53)

**Comment by EzryStIago** [comment]
Since the Uversky score is just a unitless distance, I think B is reasonable.
