### ISSUE TITLE
Enrichment coloring --- differentiate coloring between dSNP depletion and edge/non-monotonic band 

### ISSUE THREAD

**Issue by gbrannigan** [BranniganLab/blobulator#183]
For instance, the terminal blob in this protein (P0DTC2 aka the covid spike protein) should not be red. 

![image](https://user-images.githubusercontent.com/10160176/145139142-05b14095-0f6e-4d94-a07f-d2beb9ac91f3.png)

**Comment by EzryStIago** [comment]
This may or may not be a bug.
That particular blob is 41 residues long. With a cutoff of 0.4, it should have an predicted dSNP enrichment value of 0.65 (p=0.467) according to Table_S1.csv (row 3862).
Or have I misunderstood the issue?

**Comment by cpitman-11** [comment]
Add contour boundaries to the edge region of the chart, and if you're outside that region that should be a different color

**Comment by cpitman-11** [comment]
If enrichment below 1, then check
