### ISSUE TITLE
Auto-pull development site

### ISSUE THREAD

**Issue by cpitman-11** [BranniganLab/blobulator#191]
We would like the development site to pull automatically from the main branch

**Comment by ttjoseph** [comment]
I've set up a bash script /home/branniganlab/sync-devblobulator.sh that pulls the main branch into the development site. It runs at the top of each hour. Not immediate, but better than doing it manually.

**Comment by ttjoseph** [comment]
Added script /home/branniganlab/reload-devblobulator.py that calls PythonAnywhere's web API to reload the site. This script is invoked from sync-devblobulator.sh, so now, at the top of each hour the dev site should reflect the main branch with no manual intervention.
