### ISSUE TITLE
Make controls static so they don't scroll when you scroll through the tracks.  

### ISSUE THREAD

**Issue by gbrannigan** [BranniganLab/blobulator#201]
i.e. the user should be able to use the controls even while looking at lower tracks (right now, as shown below, I can't see the controls).  Most likely will require putting controls in a separate block of the website.  

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/10160176/153083555-7a87bdb7-b220-49be-a1cc-c3f803c9687e.png">

**Comment by ttjoseph** [comment]
See PR #203

**Comment by ttjoseph** [comment]
The updated PR no longer screws up printing, but the control "box" has perhaps too much whitespace
