### ISSUE TITLE
Download Data isn't working 

### ISSUE THREAD

**Issue by EzryStIago** [BranniganLab/blobulator#3]
The download data button isn't working; no download is initiated. 

OS: 
Linux, clamshell

Browsers: 
Chrome: **Version 84.0.4147.105 (Official Build) (64-bit)**
Firefox: 79.0 (64-bit)

**Comment by ruchilohia** [comment]
This is working now. But certainly the data names could be further organized

**Comment by ruchilohia** [comment]
Should be updated for mutated sequence

**Comment by ttjoseph** [comment]
See PR #25 which should now provide for user-specified mutation
