### ISSUE TITLE
human proteins are missing mutations

### ISSUE THREAD

**Issue by gbrannigan** [BranniganLab/blobulator#459]
Reproduce using 
Q6LAF9 or Q92954
<img width="1220" alt="image" src="https://github.com/BranniganLab/blobulator/assets/10160176/c1240689-41e6-4f8d-9d4b-a10c8c9cdb0a">

**Comment by cpitman-11** [comment]
Note: neither of these proteins have disease-associated variants recorded on their uniprot pages

**Comment by cpitman-11** [comment]
Closing, expected behavior
