### ISSUE TITLE
VMD blobulator needs a residue selection

### ISSUE THREAD

**Issue by RL0109** [BranniganLab/blobulator#504]
Proteins with massive chains can take up to 30 seconds to process one command. Adding a window to blobulate can reduce processing time while also blobulating only relevant sections.

**Comment by cpitman-11** [comment]
<img width="389" alt="Screenshot 2024-07-26 at 3 43 36 PM" src="https://github.com/user-attachments/assets/2ea9bc56-81d1-4ded-8fc3-ac569e2b8b3e">

**Comment by cpitman-11** [comment]
Only residues within the selection should be visible in the viewer window
