### ISSUE TITLE
Info boxes only clickable when browser window is wide

### ISSUE THREAD

**Issue by mebh** [BranniganLab/blobulator#72]
Clicking on the script "i" info icon doesn't work for all "i"s when the browser window is not very wide. 
Browser: Firefox 91.0.2

Maybe make the click area larger?

**Comment by EzryStIago** [comment]
It looks like a matter of how the js places and sizes the clickable area. It's supposed to adapt to the size of the viewport but it looks like the viewport dimensions are only gotten when the page loads.

**Comment by EzryStIago** [comment]
@mebh Is this still an issue on your end? I can't reproduce.

**Comment by mebh** [comment]
This issue looks to be resolved now-- I can't reproduce on the current live version.  So I think we're good now.
